# Site settings
title: Dave Myers | Post-punk media has-been.
email: davy@davy.us
description: > # this means to ignore newlines until "baseurl:"
Former hardcore punk and ghetto funk drummer. Former editor &amp; publisher of Paperback Jukebox, a grunge-era music, arts and culture 'zine that published in Portland, Oregon from 1991-95. Make a living as researcher, document builder, data architect. All-around has-been.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "davydog.github.io" # the base hostname & protocol for your site
twitter_username: davydog
github_username:  davydog

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
